apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dev-clusterissuer-solver-cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-dev-parameter-store
  target:
    name: dev-clusterissuer-solver-cloudflare-token
    deletionPolicy: Delete
  data:
    - secretKey: api-token
      remoteRef:
        key: /account-configuration/dev/cluster-issuer-cloudflare-token
